services:
  app.v1.stages.common.validate_api_request:
    class: App\Common\Stages\ApiRequestValidator
    arguments:
      - '@validator'

  app.v1.stages.common.make_http_response:
    class: App\Common\Response\Transformer\ApiToHttpResponseTransformer
    arguments:
      - '@serializer'
