services:
  app.v1.controller.purchase:
    class: App\Common\Controller\Controller
    bind:
      $flow: '@app.v1.purchase.flow'
    calls:
      - method: setContainer
        arguments: [ '@service_container' ]
    tags: [ 'controller.service_arguments' ]
