services:
  app.v1.purchase.http_to_api_request_transformer:
    class: App\V1\Api\Request\HttpRequestTransformer
    arguments:
      - '@serializer'
      - 'App\V1\Api\Request\Product\Purchase\ApiRequest'
      - 'json'
