### ✅ Calculate Price - valid request, with couponCode
POST http://127.0.0.1:8337/api/v1/calculate-price
Accept: application/json
Content-Type: application/json

{
  "product": 1,
  "taxNumber": "DE123456789",
  "couponCode": "P20"
}

### 🔁 Expected Response 200
# Status: 200 OK
# {
#   "price": 95.2
# }

###

### ✅ Calculate Price - valid request, without couponCode
POST http://127.0.0.1:8337/api/v1/calculate-price
Accept: application/json
Content-Type: application/json

{
    "product": 1,
    "taxNumber": "DE123456789",
    "couponCode": null
}

### 🔁 Expected Response 200
# Status: 200 OK
# {
#    "price": 119
# }

###

### ✅ Calculate Price - valid request, coupon type "fix" (10 EUR)
POST http://127.0.0.1:8337/api/v1/calculate-price
Accept: application/json
Content-Type: application/json

{
    "product": 3,
    "taxNumber": "DE123456789",
    "couponCode": "F10"
}

### 🔁 Expected Response 200
# Status: 200 OK
# {
#    "price": 1.9
# }

###

### ✅ Calculate Price - valid request, coupon type "percent" (30 %)
POST http://127.0.0.1:8337/api/v1/calculate-price
Accept: application/json
Content-Type: application/json

{
    "product": 3,
    "taxNumber": "DE123456789",
    "couponCode": "P30"
}

### 🔁 Expected Response 200
# Status: 200 OK
# {
#    "price": 8.33
# }

###

### ❌ Calculate Price - invalid taxNumber
POST http://127.0.0.1:8337/api/v1/calculate-price
Accept: application/json
Content-Type: application/json

{
    "product": 1,
    "taxNumber": "DE123",
    "couponCode": "P20"
}

### 🔁 Expected Response 400
# Status: 400 Bad Request
# {
#    "errors": [
#        {
#            "field": "taxNumber",
#            "message": "Invalid tax number."
#        }
#    ]
# }

###

### ❌ Calculate Price - invalid taxNumber type
POST http://127.0.0.1:8337/api/v1/calculate-price
Accept: application/json
Content-Type: application/json

{
    "product": 1,
    "taxNumber": null,
    "couponCode": "P20"
}

### 🔁 Expected Response 422
# Status: 422 Unprocessable Content
# {
#    "errors": [
#        {
#            "field": "taxNumber",
#            "message": "The type of the \"taxNumber\" must be one of types \"string\" (null given)"
#        }
#    ]
# }

###

### ❌ Calculate Price - invalid couponCode
POST http://127.0.0.1:8337/api/v1/calculate-price
Accept: application/json
Content-Type: application/json

{
    "product": 1,
    "taxNumber": "DE123456789",
    "couponCode": "P"
}

### 🔁 Expected Response 400
# Status: 400 Bad Request
# {
#    "errors": [
#        {
#            "field": "couponCode",
#            "message": "The coupon \"P\" does not exist"
#        },
#        {
#            "field": "couponCode",
#            "message": "This value is too short. It should have 2 characters or more."
#        }
#    ]
# }

###

### ❌ Calculate Price - invalid product
POST http://127.0.0.1:8337/api/v1/calculate-price
Accept: application/json
Content-Type: application/json

{
    "product": 777,
    "taxNumber": "DE123456789",
    "couponCode": "F5"
}

### 🔁 Expected Response 404
# Status: 404 Not found
# {
#    "message": "Product entity id \"777\" not found."
# }

###
