app.calculate_price:
    path: /calculate-price
    defaults: {
        _controller: app.v1.controller.calculate_price::index
    }
    methods: [ POST ]

app.purchase:
  path: /purchase
  defaults: {
    _controller: app.v1.controller.purchase::index
  }
  methods: [ POST ]
