services:
  app.v1.controller.calculate_price:
    class: App\Common\Controller\Controller
    bind:
      $flow: '@app.v1.calculate_price.flow'
    calls:
      - method: setContainer
        arguments: [ '@service_container' ]
    tags: [ 'controller.service_arguments' ]
